<a href="https://colab.research.google.com/github/Alfiina/ICT_INTERNSHIP/blob/day2/Day2_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
sumlist=[]
for num1,num2 in zip(list1,list2):
  sumlist.append(num1+num2)
sumlist

[6, 8, 10, 12]

In [ ]:
import numpy as np

In [ ]:
arr1=np.array(list1)

In [ ]:
arr2=np.array(list2)

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr2

array([5, 6, 7, 8])

In [ ]:
sumlist=arr1+arr2

In [ ]:
sumlist

array([ 6,  8, 10, 12])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
list3=[[2,3,5],[1,9,4]]

In [ ]:
list3

[[2, 3, 5], [1, 9, 4]]

In [ ]:
arr4=np.array(list3)

In [ ]:
arr4.ndim

2

In [ ]:
arr4.shape

(2, 3)

In [ ]:
arr3=[1,2,3,4,5,6,7]
arr3=np.arange(6)

In [ ]:
arr4

array([[2, 3, 5],
       [1, 9, 4]])

In [ ]:
arr3

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr5=arr3.reshape(2,3)

In [ ]:
arr3.mean()

2.5

In [ ]:
np.median(arr3)

2.5

In [ ]:
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

array([[0.5190061 , 0.5934259 , 0.86841609, 0.79524818],
       [0.31679923, 0.71774713, 0.90212619, 0.09502059],
       [0.52314969, 0.74417279, 0.24759016, 0.49281375]])

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/auto-mpg.csv')